import type { Contact } from "@/lib/types"

// Sample tags for contacts
const sampleTags = [
  { id: "florida", name: "Florida", color: "blue" },
  { id: "residential", name: "Residential", color: "green" },
  { id: "commercial", name: "Commercial", color: "purple" },
  { id: "multi-unit", name: "Multi-Unit", color: "amber" },
  { id: "high-value", name: "High Value", color: "red" },
  { id: "new-contact", name: "New Contact", color: "indigo" },
]

// Generate mock contacts with realistic data
export const mockContacts: Contact[] = [
  {
    id: "contact1",
    firstName: "John",
    lastName: "Smith",
    phone: "(555) 123-4567",
    email: "john.smith@example.com",
    propertyAddress: "123 Main Street, Orlando, FL 32801",
    propertyType: "single-family",
    propertyValue: 350000,
    debtOwed: 220000,
    dealStatus: "new",
    tags: [sampleTags[0], sampleTags[1]],
    createdAt: "2023-01-15T10:30:00Z",
    notes: "Interested in selling within 6 months. Has some equity but needs repairs.",
  },
  {
    id: "contact2",
    firstName: "Sarah",
    lastName: "Johnson",
    phone: "(555) 234-5678",
    email: "sarah.johnson@example.com",
    propertyAddress: "456 Oak Avenue, Tampa, FL 33602",
    propertyType: "duplex",
    propertyValue: 425000,
    debtOwed: 310000,
    dealStatus: "qualified",
    tags: [sampleTags[0], sampleTags[3]],
    createdAt: "2023-02-22T14:15:00Z",
    notes: "Current rental property with tenants. Looking to sell and upgrade to larger multi-family.",
  },
  {
    id: "contact3",
    firstName: "Michael",
    lastName: "Brown",
    phone: "(555) 345-6789",
    email: "michael.brown@example.com",
    propertyAddress: "789 Pine Street, Miami, FL 33101",
    propertyType: "multi-family",
    propertyValue: 780000,
    debtOwed: 450000,
    dealStatus: "negotiation",
    tags: [sampleTags[0], sampleTags[2], sampleTags[4]],
    createdAt: "2023-03-10T09:45:00Z",
    notes: "8-unit apartment building. Owner retiring and motivated to sell quickly.",
  },
  {
    id: "contact4",
    firstName: "Emily",
    lastName: "Davis",
    phone: "(555) 456-7890",
    email: "emily.davis@example.com",
    propertyAddress: "321 Elm Drive, Jacksonville, FL 32202",
    propertyType: "triplex",
    propertyValue: 520000,
    debtOwed: 380000,
    dealStatus: "follow_up",
    tags: [sampleTags[0], sampleTags[3]],
    createdAt: "2023-04-05T16:20:00Z",
    notes: "Needs to sell due to job relocation. Property needs minor repairs.",
  },
  {
    id: "contact5",
    firstName: "David",
    lastName: "Wilson",
    phone: "(555) 567-8901",
    email: "david.wilson@example.com",
    propertyAddress: "654 Maple Lane, Fort Lauderdale, FL 33301",
    propertyType: "single-family",
    propertyValue: 620000,
    debtOwed: 410000,
    dealStatus: "closed",
    tags: [sampleTags[0], sampleTags[1], sampleTags[5]],
    createdAt: "2023-05-18T11:10:00Z",
    notes: "Deal closed successfully. Good candidate for referrals.",
  },
  {
    id: "contact6",
    firstName: "Lisa",
    lastName: "Martinez",
    phone: "(555) 678-9012",
    email: "lisa.martinez@example.com",
    propertyAddress: "987 Cedar Court, Naples, FL 34102",
    propertyType: "quadplex",
    propertyValue: 890000,
    debtOwed: 650000,
    dealStatus: "lost",
    tags: [sampleTags[0], sampleTags[3], sampleTags[4]],
    createdAt: "2023-06-30T13:25:00Z",
    notes: "Decided to refinance instead of selling. Follow up in 1 year.",
  },
  {
    id: "contact7",
    firstName: "Robert",
    lastName: "Anderson",
    phone: "(555) 789-0123",
    email: "robert.anderson@example.com",
    propertyAddress: "246 Birch Street, Sarasota, FL 34236",
    propertyType: "single-family",
    propertyValue: 475000,
    debtOwed: 290000,
    dealStatus: "new",
    tags: [sampleTags[0], sampleTags[1], sampleTags[5]],
    createdAt: "2023-07-12T15:40:00Z",
    notes: "Inherited property. Not local and interested in quick sale.",
  },
  {
    id: "contact8",
    firstName: "Jennifer",
    lastName: "Taylor",
    phone: "(555) 890-1234",
    email: "jennifer.taylor@example.com",
    propertyAddress: "135 Willow Way, Clearwater, FL 33755",
    propertyType: "duplex",
    propertyValue: 510000,
    debtOwed: 375000,
    dealStatus: "qualified",
    tags: [sampleTags[0], sampleTags[3]],
    createdAt: "2023-08-25T10:05:00Z",
    notes: "Current owner-occupied with rental unit. Looking to downsize.",
  },
  {
    id: "contact9",
    firstName: "Christopher",
    lastName: "Moore",
    phone: "(555) 901-2345",
    email: "christopher.moore@example.com",
    propertyAddress: "864 Spruce Avenue, Pensacola, FL 32502",
    propertyType: "multi-family",
    propertyValue: 950000,
    debtOwed: 720000,
    dealStatus: "negotiation",
    tags: [sampleTags[0], sampleTags[2], sampleTags[4]],
    createdAt: "2023-09-08T14:50:00Z",
    notes: "12-unit building with management issues. Owner wants out.",
  },
  {
    id: "contact10",
    firstName: "Amanda",
    lastName: "White",
    phone: "(555) 012-3456",
    email: "amanda.white@example.com",
    propertyAddress: "753 Aspen Circle, Tallahassee, FL 32301",
    propertyType: "single-family",
    propertyValue: 390000,
    debtOwed: 260000,
    dealStatus: "follow_up",
    tags: [sampleTags[0], sampleTags[1]],
    createdAt: "2023-10-17T09:30:00Z",
    notes: "Divorce situation. Both parties motivated to sell quickly.",
  },
]
